name: Chipyard Megaboom Benchmark

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  binary-tests:
    name: Binary test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/antmicro/megaboom-cpu-benchmarking:latest
      volumes:
        - /usr/share/dotnet:/usr/share/dotnet
        - /usr/local/lib/android:/usr/local/lib/android
        - /opt/ghc:/opt/ghc
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        CONFIG: ["RocketConfig", "MegaBoomConfig"]
        BINARY: ["../../tests/hello.riscv", "../../software/coremark/riscv-coremark/coremark.bare.riscv"]
    env:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - name: Increase build space
        run: |
          echo "Before cleanup"
          df -H
          rm -rf /usr/share/dotnet/*
          rm -rf /usr/local/lib/android/*
          rm -rf /opt/ghc/*
          echo "After cleanup"
          df -H
      - name: install chipyard
        id: install_chipyard
        run: |
          git clone https://github.com/ucb-bar/chipyard.git
          pushd chipyard
              git checkout 1.11.0
              ./build-setup.sh riscv-tools -s 4 -s 6 -s 7 -s 8 -s 9
          popd
      - name: Binary test
        id: binary_test
        run: |
          pushd chipyard
            . /root/conda/etc/profile.d/conda.sh
            conda activate
            source env.sh
            git submodule update --init --recursive software/coremark
            pushd software/coremark
              ./build.sh
            popd
            pushd sims/verilator
              make run-binary CONFIG=${{ matrix.CONFIG }} BINARY=${{ matrix.BINARY }}
            popd
          popd


